### ISSUE TITLE
Problem with value of Lactate of different methods

### ISSUE THREAD

**Issue by IOSUT** [fmmattioni/lactater#4]
I don´t know why but the lactatue value of different methos and different athletes it´s the same, entering the different data of lactate of different athletes it couldn´t be the same...some help? thanks

**Comment by fmmattioni** [comment]
Hi, I am not sure I understand your question. Could you please provide a reproducible example?

**Comment by IOSUT** [comment]
Thanks Felipe for your time, i was a obvious error... I haven't change the "demo data"... In scribd function... Thanks for your contributions.
