### ISSUE TITLE
Determination of maximal incomplete stage

### ISSUE THREAD

**Issue by IOSUT** [fmmattioni/lactater#5]
Hi Felipe, one cuestion I couldn´t see the function to determinate the last value of lactate/intensity/ calculated and how is it.

I understandt that with time uncomplete, lactate and intensity in last stage of graded exercise test, lactater calculate the "estimated" value of lactate at final point  right? 

Like Maximal aerobic power in calculations of other test right?

Thanks one time more. :D

**Comment by fmmattioni** [comment]
Hi @IOSUT,

If the last stage was not completed, then the package simply calculates the exercise intensity at that point, which is done via a simple linear interpolation. Then, you are required to input the lactate value associated with it – and that is the lactate value that is used.

Does that make sense?

**Comment by IOSUT** [comment]
Thanks so much, now I have undertood it!

**Comment by IOSUT** [comment]
Thanks !
