### ISSUE TITLE
error on row 1 with mutate

### ISSUE THREAD

**Issue by IOSUT** [fmmattioni/lactater#6]
Hi, Felipe, thanks for your contribution.

Recently some works different from previous version, maybe due to new version of R studio.

the error is the next:

Error in `dplyr::mutate()`:
ℹ In argument: `results = switch(...)`.
ℹ In row 1.
Caused by error in `dplyr::mutate()`:
ℹ In argument: `plot = list(plot_lactate(data_processed = data, method =
  method))`.
ℹ In row 1.
Caused by error in `X.noV[, nomiOK, drop = FALSE]`:
! número incorreto de dimensiones
Backtrace:
  1. lactater::lactate_threshold(...)
 26. lactater:::plot_lactate(data_processed = data, method = method)
 28. segmented::predict.segmented(object = segmented_object, newdata = data.frame(intensity = method_intensity))

Thanks for your contrinbution

**Comment by jtgreens** [comment]
Hi Felipre,

I am also receiving a similar error as mentioned above.

```r
library(lactater)
tibble::tribble(
  ~step, ~length, ~intensity, ~lactate, ~heart_rate,
  0L,      0L,         0L,      1.5,        100L,
  1L,      3L,       111L,        2,        124L,
  2L,      3L,       145L,      1.2,        130L,
  3L,      3L,       159L,      1.25,        147L,
  4L,      3L,       182L,      2.2,        157L,
  5L,      3L,       204L,      3.4,        164L,
  6L,      3L,       226L,      6.3,        173L
) %>%
  lactate_threshold(
    .data = .,
    intensity_column = 'intensity',
    lactate_column = 'lactate',
    heart_rate_column = 'heart_rate',
    method = c('Log-log', 'OBLA', 'Bsln+', 'Dmax', 'LTP', 'LTratio'),
    fit = '3rd degree polynomial',
    include_baseline = FALSE,
    sport = 'cycling',
    loglog_restrainer = 0.75,
    plot = TRUE
  )
```


Error in `dplyr::mutate()`:
ℹ In argument: `results = switch(...)`.
ℹ In row 1.
Caused by error in `dplyr::mutate()`:
ℹ In argument: `plot = list(plot_lactate(data_processed = data, method = method))`.
ℹ In row 1.
Caused by error in `X.noV[, nomiOK, drop = FALSE]`:
! incorrect number of dimensions
Run `rlang::last_trace()` to see where the error occurred.

Thank you for the work that you do, great resource!

**Comment by IOSUT** [comment]
Answer from Felipe, very watchful.

Hi, this is being caused by an update of another package that lactater relies on. This has already been reported and the fix should be available soon..

Thanks

**Comment by fmmattioni** [comment]
Hi,

This was caused by a third-party package called `segmented`. The fix has just been released. Please, install the new segmented version with `install.packages('segmented', type = 'source')` and the problem should be fixed.
